import { FormEvent, PointerEvent as ReactPointerEvent, useEffect, useMemo, useState } from "react";
import {
  Bot,
  Braces,
  CheckCircle2,
  ChevronRight,
  CircleDot,
  Copy,
  GitBranch,
  Link2,
  ListChecks,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  ShieldCheck,
  Sparkles,
  Trash2,
  Workflow as WorkflowIcon,
  X,
} from "lucide-react";

type Locale = "ar" | "en";
const API_URL = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? "http://localhost:8000" : window.location.origin);

type CatalogNode = {
  type: string;
  category: string;
  label_ar: string;
  label_en: string;
  description_ar: string;
  description_en: string;
};

type WorkflowSummary = {
  id: string;
  name: string;
  description?: string | null;
  status: "draft" | "active" | "disabled";
  version: number;
  created_at: string;
  updated_at: string;
  nodes_count: number;
  edges_count: number;
};

type WorkflowNode = {
  id?: string;
  node_key: string;
  node_type: string;
  title: string;
  config: Record<string, unknown>;
  position_x: number;
  position_y: number;
};

type WorkflowEdge = {
  id?: string;
  source_node_key: string;
  target_node_key: string;
  route: string;
};

type WorkflowGraph = {
  workflow: WorkflowSummary;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
};

type AutomationRun = {
  id: string;
  workflow_id: string;
  status: string;
  trigger_type: string;
  input: Record<string, unknown>;
  output: Record<string, unknown>;
  error?: string | null;
  started_at?: string | null;
  finished_at?: string | null;
  created_at: string;
  node_runs: Array<{
    id: string;
    node_key: string;
    status: string;
    output: Record<string, unknown>;
    error?: string | null;
  }>;
  approvals: Array<{
    id: string;
    node_id: string;
    status: string;
    prompt: string;
    reviewed_at?: string | null;
  }>;
};

async function automationApi<T>(path: string, token: string, init?: RequestInit): Promise<T> {
  const headers = new Headers(init?.headers);
  headers.set("Authorization", `Bearer ${token}`);
  if (init?.body) headers.set("Content-Type", "application/json");
  const response = await fetch(`${API_URL}${path}`, { ...init, headers });
  const body = await response.json().catch(() => null);
  if (!response.ok) throw new Error(body?.detail || `HTTP ${response.status}`);
  return body as T;
}

function nodeCategory(nodeType: string) {
  return nodeType.split(".")[0] || "action";
}

function nodeIcon(nodeType: string) {
  const category = nodeCategory(nodeType);
  if (category === "trigger") return CircleDot;
  if (category === "data") return Search;
  if (category === "logic") return GitBranch;
  if (category === "approval") return ShieldCheck;
  if (category === "output") return CheckCircle2;
  if (nodeType.includes("prepare_message")) return Bot;
  return Sparkles;
}

function defaultConfig(type: string): Record<string, unknown> {
  if (type === "data.inventory_search") return { limit: 10 };
  if (type === "data.lead_lookup") return {};
  if (type === "condition.field_equals") return { field: "input.intent", value: "interested" };
  if (type === "action.create_task") return { title: "متابعة {{lead.full_name}}", notes: "Generated by Automation Studio", due_hours: 24 };
  if (type === "action.prepare_message") return { template: "مرحبًا {{lead.full_name}}، لدينا {{inventory_count}} خيارات متاحة." };
  if (type === "action.internal_note") return { body: "Automation note" };
  if (type === "action.seo_sync_project") return {};
  if (type === "approval.human") return { prompt: "اعتماد تنفيذ الخطوة التالية؟" };
  if (type === "output.summary") return { fields: ["inventory_count", "prepared_message"] };
  return {};
}

export default function AutomationStudio({ token, locale }: { token: string; locale: Locale }) {
  const ar = locale === "ar";
  const [catalog, setCatalog] = useState<CatalogNode[]>([]);
  const [workflows, setWorkflows] = useState<WorkflowSummary[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [graph, setGraph] = useState<WorkflowGraph | null>(null);
  const [runs, setRuns] = useState<AutomationRun[]>([]);
  const [selectedNodeKey, setSelectedNodeKey] = useState("");
  const [configText, setConfigText] = useState("{}");
  const [runInput, setRunInput] = useState('{"intent":"interested"}');
  const [edgeSource, setEdgeSource] = useState("");
  const [edgeTarget, setEdgeTarget] = useState("");
  const [edgeRoute, setEdgeRoute] = useState("success");
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  const selectedNode = useMemo(
    () => graph?.nodes.find((node) => node.node_key === selectedNodeKey) || null,
    [graph, selectedNodeKey],
  );

  async function loadWorkflows() {
    const data = await automationApi<WorkflowSummary[]>("/api/v1/automations", token);
    setWorkflows(data);
    setSelectedId((current) => current || data[0]?.id || "");
  }

  async function loadCatalog() {
    const data = await automationApi<{ nodes: CatalogNode[] }>("/api/v1/automations/catalog", token);
    setCatalog(data.nodes);
  }

  async function loadGraph(workflowId: string) {
    if (!workflowId) {
      setGraph(null);
      setRuns([]);
      return;
    }
    const [graphData, runData] = await Promise.all([
      automationApi<WorkflowGraph>(`/api/v1/automations/${workflowId}`, token),
      automationApi<AutomationRun[]>(`/api/v1/automations/${workflowId}/runs`, token),
    ]);
    setGraph(graphData);
    setRuns(runData);
    setSelectedNodeKey("");
    setConfigText("{}");
  }

  async function refreshAll() {
    setBusy("refresh");
    setError("");
    try {
      await Promise.all([loadCatalog(), loadWorkflows()]);
      if (selectedId) await loadGraph(selectedId);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Load failed");
    } finally {
      setBusy("");
    }
  }

  useEffect(() => {
    void (async () => {
      try {
        await Promise.all([loadCatalog(), loadWorkflows()]);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Load failed");
      }
    })();
  }, [token]);

  useEffect(() => {
    void loadGraph(selectedId).catch((err) => setError(err instanceof Error ? err.message : "Load failed"));
  }, [selectedId]);

  useEffect(() => {
    if (selectedNode) setConfigText(JSON.stringify(selectedNode.config || {}, null, 2));
  }, [selectedNodeKey]);

  async function createWorkflow(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    setBusy("create"); setError(""); setNotice("");
    try {
      const created = await automationApi<WorkflowSummary>("/api/v1/automations", token, {
        method: "POST",
        body: JSON.stringify({
          name: String(data.get("name") || "").trim(),
          description: String(data.get("description") || "").trim() || null,
        }),
      });
      form.reset();
      await loadWorkflows();
      setSelectedId(created.id);
      setNotice(ar ? "تم إنشاء Workflow جديد." : "Workflow created.");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Create failed");
    } finally { setBusy(""); }
  }

  function addNode(item: CatalogNode) {
    if (!graph) return;
    if (runs.length) {
      setError(ar ? "هذا الـWorkflow له سجل تشغيل. استخدم «نسخ» قبل تعديل الرسم." : "This workflow has run history. Duplicate it before editing the graph.");
      return;
    }
    const index = graph.nodes.length + 1;
    const key = `${item.type.replace(/[^a-z0-9]+/gi, "_")}_${index}`;
    const node: WorkflowNode = {
      node_key: key,
      node_type: item.type,
      title: ar ? item.label_ar : item.label_en,
      config: defaultConfig(item.type),
      position_x: 80 + ((index - 1) % 4) * 230,
      position_y: 80 + Math.floor((index - 1) / 4) * 150,
    };
    setGraph({ ...graph, nodes: [...graph.nodes, node] });
    setSelectedNodeKey(key);
  }

  function updateNode(patch: Partial<WorkflowNode>) {
    if (!graph || !selectedNode) return;
    setGraph({
      ...graph,
      nodes: graph.nodes.map((node) => node.node_key === selectedNode.node_key ? { ...node, ...patch } : node),
    });
  }

  function saveConfig() {
    if (!selectedNode) return;
    try {
      const value = JSON.parse(configText);
      updateNode({ config: value });
      setNotice(ar ? "تم تطبيق إعدادات العقدة محليًا. اضغط حفظ الرسم لتثبيتها." : "Node settings applied locally. Save the graph to persist them.");
      setError("");
    } catch {
      setError(ar ? "إعدادات العقدة ليست JSON صحيحًا." : "Node configuration is not valid JSON.");
    }
  }

  function removeNode(nodeKey: string) {
    if (!graph || runs.length) return;
    setGraph({
      ...graph,
      nodes: graph.nodes.filter((node) => node.node_key !== nodeKey),
      edges: graph.edges.filter((edge) => edge.source_node_key !== nodeKey && edge.target_node_key !== nodeKey),
    });
    if (selectedNodeKey === nodeKey) setSelectedNodeKey("");
  }

  function addEdge() {
    if (!graph || !edgeSource || !edgeTarget || edgeSource === edgeTarget) return;
    if (graph.edges.some((edge) => edge.source_node_key === edgeSource && edge.target_node_key === edgeTarget && edge.route === edgeRoute)) return;
    setGraph({
      ...graph,
      edges: [...graph.edges, { source_node_key: edgeSource, target_node_key: edgeTarget, route: edgeRoute }],
    });
    setEdgeSource("");
    setEdgeTarget("");
  }

  function removeEdge(index: number) {
    if (!graph || runs.length) return;
    setGraph({ ...graph, edges: graph.edges.filter((_, edgeIndex) => edgeIndex !== index) });
  }

  function dragNode(event: ReactPointerEvent<HTMLDivElement>, node: WorkflowNode) {
    if (!graph || runs.length) return;
    const startX = event.clientX;
    const startY = event.clientY;
    const originX = node.position_x;
    const originY = node.position_y;
    const target = event.currentTarget;
    target.setPointerCapture(event.pointerId);

    const move = (native: PointerEvent) => {
      const x = Math.max(10, Math.min(1800, originX + native.clientX - startX));
      const y = Math.max(10, Math.min(1100, originY + native.clientY - startY));
      setGraph((current) => current ? {
        ...current,
        nodes: current.nodes.map((item) => item.node_key === node.node_key ? { ...item, position_x: Math.round(x), position_y: Math.round(y) } : item),
      } : current);
    };
    const up = () => {
      window.removeEventListener("pointermove", move);
      window.removeEventListener("pointerup", up);
    };
    window.addEventListener("pointermove", move);
    window.addEventListener("pointerup", up);
  }

  async function saveGraph() {
    if (!graph) return;
    setBusy("save"); setError(""); setNotice("");
    try {
      const saved = await automationApi<WorkflowGraph>(`/api/v1/automations/${graph.workflow.id}/graph`, token, {
        method: "PUT",
        body: JSON.stringify({
          nodes: graph.nodes.map(({ node_key, node_type, title, config, position_x, position_y }) => ({ node_key, node_type, title, config, position_x, position_y })),
          edges: graph.edges.map(({ source_node_key, target_node_key, route }) => ({ source_node_key, target_node_key, route })),
        }),
      });
      setGraph(saved);
      await loadWorkflows();
      setNotice(ar ? "تم حفظ الرسم والتحقق من عدم وجود حلقات." : "Graph saved and validated as acyclic.");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Save failed");
    } finally { setBusy(""); }
  }

  async function duplicateWorkflow() {
    if (!graph) return;
    setBusy("duplicate"); setError("");
    try {
      const duplicate = await automationApi<WorkflowGraph>(`/api/v1/automations/${graph.workflow.id}/duplicate`, token, { method: "POST" });
      await loadWorkflows();
      setSelectedId(duplicate.workflow.id);
      setNotice(ar ? "تم إنشاء نسخة قابلة للتعديل." : "Editable copy created.");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Duplicate failed");
    } finally { setBusy(""); }
  }

  async function toggleWorkflow() {
    if (!graph) return;
    const next = graph.workflow.status === "active" ? "disabled" : "active";
    setBusy("toggle"); setError("");
    try {
      await automationApi(`/api/v1/automations/${graph.workflow.id}`, token, {
        method: "PATCH",
        body: JSON.stringify({ status: next }),
      });
      await loadGraph(graph.workflow.id);
      await loadWorkflows();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Update failed");
    } finally { setBusy(""); }
  }

  async function runWorkflow() {
    if (!graph) return;
    setBusy("run"); setError(""); setNotice("");
    try {
      const input = JSON.parse(runInput || "{}");
      const result = await automationApi<AutomationRun>(`/api/v1/automations/${graph.workflow.id}/run`, token, {
        method: "POST",
        body: JSON.stringify({ trigger_type: "manual", input }),
      });
      await loadGraph(graph.workflow.id);
      setNotice(result.status === "waiting_approval"
        ? (ar ? "توقف التشغيل عند خطوة اعتماد بشري." : "Run paused for human approval.")
        : (ar ? `انتهى التشغيل بالحالة: ${result.status}` : `Run finished: ${result.status}`));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Run failed");
    } finally { setBusy(""); }
  }

  async function decide(approvalId: string, decision: "approved" | "rejected") {
    setBusy(approvalId); setError("");
    try {
      await automationApi(`/api/v1/automations/approvals/${approvalId}/decision`, token, {
        method: "POST",
        body: JSON.stringify({ decision, note: ar ? "قرار من Automation Studio" : "Decision from Automation Studio" }),
      });
      if (graph) await loadGraph(graph.workflow.id);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Approval failed");
    } finally { setBusy(""); }
  }

  const paletteGroups = useMemo(() => {
    const groups: Record<string, CatalogNode[]> = {};
    for (const item of catalog) (groups[item.category] ||= []).push(item);
    return groups;
  }, [catalog]);

  return <div className="automationStudio">
    <section className="automationHero panel">
      <div>
        <span className="eyebrow">VISUAL AUTOMATION STUDIO</span>
        <h2>{ar ? "مصمم العمليات الآلية" : "Visual Workflow Builder"}</h2>
        <p>{ar
          ? "اربط CRM والمخزون وSEO والموافقات والمهام في Workflow مرئي. التنفيذ داخلي وآمن؛ لا يوجد PowerShell أو Shell مخفي."
          : "Connect CRM, inventory, SEO, approvals and tasks in a visual workflow. Execution uses safe internal actions—no hidden PowerShell or shell commands."}</p>
      </div>
      <div className="automationSafety"><ShieldCheck size={18}/><span>{ar ? "لا يتم إرسال رسائل خارجية تلقائيًا من عقدة تجهيز الرد." : "Prepare-message nodes never imply external delivery."}</span></div>
    </section>

    {error && <div className="systemError">{error}</div>}
    {notice && <div className="successNotice">{notice}</div>}

    <div className="automationShell">
      <aside className="panel automationLeft">
        <div className="panelHead"><h3>{ar ? "العمليات" : "Workflows"}</h3><button className="iconButton miniIcon" onClick={() => void refreshAll()}><RefreshCw size={15} className={busy==="refresh" ? "spin" : ""}/></button></div>
        <form className="automationCreate" onSubmit={createWorkflow}>
          <input name="name" required placeholder={ar ? "اسم Workflow" : "Workflow name"}/>
          <input name="description" placeholder={ar ? "وصف مختصر" : "Short description"}/>
          <button className="secondaryButton" disabled={busy==="create"}><Plus size={15}/>{ar ? "جديد" : "New"}</button>
        </form>
        <div className="automationWorkflowList">
          {workflows.map((workflow) => <button key={workflow.id} className={selectedId===workflow.id ? "automationWorkflow active" : "automationWorkflow"} onClick={() => setSelectedId(workflow.id)}>
            <WorkflowIcon size={17}/>
            <div><strong>{workflow.name}</strong><span>{workflow.nodes_count} nodes · v{workflow.version}</span></div>
            <span className={`statusBadge status-${workflow.status}`}>{workflow.status}</span>
          </button>)}
        </div>

        <div className="automationPalette">
          <span className="eyebrow">{ar ? "مكتبة العقد" : "NODE LIBRARY"}</span>
          {Object.entries(paletteGroups).map(([category, items]) => <div className="paletteGroup" key={category}>
            <strong>{category}</strong>
            {items.map((item) => {
              const Icon = nodeIcon(item.type);
              return <button key={item.type} onClick={() => addNode(item)} disabled={!graph || runs.length > 0}>
                <Icon size={15}/><span>{ar ? item.label_ar : item.label_en}</span><Plus size={13}/>
              </button>;
            })}
          </div>)}
        </div>
      </aside>

      <main className="panel automationCanvasPanel">
        {!graph ? <div className="automationEmpty"><WorkflowIcon size={38}/><h3>{ar ? "أنشئ Workflow أو اختر واحدًا" : "Create or select a workflow"}</h3></div> : <>
          <div className="automationToolbar">
            <div>
              <strong>{graph.workflow.name}</strong>
              <span>v{graph.workflow.version} · {graph.workflow.status}</span>
            </div>
            <div className="automationToolbarActions">
              <button className="secondaryButton" onClick={() => void duplicateWorkflow()}><Copy size={15}/>{ar ? "نسخ" : "Duplicate"}</button>
              <button className="secondaryButton" onClick={() => void toggleWorkflow()}>{graph.workflow.status==="active" ? (ar?"تعطيل":"Disable") : (ar?"تفعيل":"Activate")}</button>
              <button className="primaryButton" onClick={() => void saveGraph()} disabled={busy==="save" || runs.length>0}><Save size={15}/>{ar ? "حفظ الرسم" : "Save graph"}</button>
            </div>
          </div>

          <div className="automationCanvas">
            <svg className="automationEdges" width="2000" height="1200" aria-hidden="true">
              <defs>
                <marker id="arrowhead" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
                  <path d="M0,0 L0,6 L7,3 z" />
                </marker>
              </defs>
              {graph.edges.map((edge, index) => {
                const source = graph.nodes.find((node) => node.node_key===edge.source_node_key);
                const target = graph.nodes.find((node) => node.node_key===edge.target_node_key);
                if (!source || !target) return null;
                const x1=source.position_x+184, y1=source.position_y+43, x2=target.position_x, y2=target.position_y+43;
                const mid=Math.max(55,Math.abs(x2-x1)*0.45);
                return <g key={index}>
                  <path className={`automationEdge route-${edge.route}`} d={`M ${x1} ${y1} C ${x1+mid} ${y1}, ${x2-mid} ${y2}, ${x2} ${y2}`} markerEnd="url(#arrowhead)"/>
                  <text x={(x1+x2)/2} y={(y1+y2)/2-7}>{edge.route}</text>
                </g>;
              })}
            </svg>

            {graph.nodes.map((node) => {
              const Icon=nodeIcon(node.node_type);
              return <div
                key={node.node_key}
                className={selectedNodeKey===node.node_key ? `automationNode ${nodeCategory(node.node_type)} selected` : `automationNode ${nodeCategory(node.node_type)}`}
                style={{left:node.position_x,top:node.position_y}}
                onPointerDown={(event)=>dragNode(event,node)}
                onClick={()=>setSelectedNodeKey(node.node_key)}
              >
                <div className="automationNodeIcon"><Icon size={18}/></div>
                <div><span>{node.node_type}</span><strong>{node.title}</strong></div>
                {!runs.length && <button className="automationNodeDelete" onPointerDown={(e)=>e.stopPropagation()} onClick={(e)=>{e.stopPropagation();removeNode(node.node_key);}}><X size={13}/></button>}
              </div>;
            })}
          </div>

          {!runs.length && <div className="edgeComposer">
            <Link2 size={16}/>
            <select value={edgeSource} onChange={(e)=>setEdgeSource(e.target.value)}><option value="">{ar?"من عقدة":"From node"}</option>{graph.nodes.map(n=><option key={n.node_key} value={n.node_key}>{n.title}</option>)}</select>
            <ChevronRight size={15}/>
            <select value={edgeTarget} onChange={(e)=>setEdgeTarget(e.target.value)}><option value="">{ar?"إلى عقدة":"To node"}</option>{graph.nodes.map(n=><option key={n.node_key} value={n.node_key}>{n.title}</option>)}</select>
            <select value={edgeRoute} onChange={(e)=>setEdgeRoute(e.target.value)}><option value="success">success</option><option value="true">true</option><option value="false">false</option><option value="approved">approved</option><option value="rejected">rejected</option></select>
            <button className="secondaryButton" onClick={addEdge}><Plus size={14}/>{ar?"ربط":"Connect"}</button>
          </div>}

          {!runs.length && graph.edges.length>0 && <div className="edgeList">{graph.edges.map((edge,index)=><span key={index}>{edge.source_node_key} → {edge.target_node_key} <b>{edge.route}</b><button onClick={()=>removeEdge(index)}><Trash2 size={12}/></button></span>)}</div>}
        </>}
      </main>

      <aside className="panel automationRight">
        <div className="panelHead"><h3>{ar ? "الإعدادات والتشغيل" : "Inspector & Runs"}</h3><Braces size={17}/></div>
        {selectedNode ? <div className="nodeInspector">
          <span className="eyebrow">{selectedNode.node_type}</span>
          <label>{ar?"العنوان":"Title"}<input value={selectedNode.title} onChange={(e)=>updateNode({title:e.target.value})} disabled={runs.length>0}/></label>
          <label>{ar?"إعدادات JSON":"JSON config"}<textarea rows={10} value={configText} onChange={(e)=>setConfigText(e.target.value)} disabled={runs.length>0}/></label>
          {!runs.length && <button className="secondaryButton" onClick={saveConfig}><Save size={14}/>{ar?"تطبيق الإعدادات":"Apply config"}</button>}
        </div> : <div className="inspectorHint">{ar ? "اضغط على أي عقدة لعرض إعداداتها." : "Select a node to inspect its settings."}</div>}

        {graph && <div className="automationRunBox">
          <div className="opsTitle"><Play size={17}/><strong>{ar?"تشغيل تجريبي":"Manual run"}</strong></div>
          <textarea rows={6} value={runInput} onChange={(e)=>setRunInput(e.target.value)}/>
          <button className="primaryButton" onClick={() => void runWorkflow()} disabled={busy==="run"}>{busy==="run"?<RefreshCw className="spin" size={15}/>:<Play size={15}/>} {ar?"Run Workflow":"Run Workflow"}</button>
        </div>}

        <div className="automationRuns">
          <div className="opsTitle"><ListChecks size={17}/><strong>{ar?"آخر التشغيلات":"Recent runs"}</strong></div>
          {runs.map((run)=><article key={run.id}>
            <div><strong>{run.status}</strong><span>{new Date(run.created_at).toLocaleString(ar?"ar-EG":"en-US")}</span></div>
            <span className={`statusBadge status-${run.status}`}>{run.node_runs.length} nodes</span>
            {run.error && <p>{run.error}</p>}
            {run.approvals.filter(a=>a.status==="pending").map((approval)=><div className="approvalCard" key={approval.id}>
              <ShieldCheck size={16}/><p>{approval.prompt}</p>
              <button onClick={()=>void decide(approval.id,"approved")} disabled={busy===approval.id}>{ar?"اعتماد":"Approve"}</button>
              <button onClick={()=>void decide(approval.id,"rejected")} disabled={busy===approval.id}>{ar?"رفض":"Reject"}</button>
            </div>)}
          </article>)}
          {!runs.length && <div className="inspectorHint">{ar?"لا يوجد سجل تشغيل بعد.":"No run history yet."}</div>}
        </div>
      </aside>
    </div>
  </div>;
}
